[tox]
envlist = py310, lint
isolated_build = True

[testenv]
sitepackages = true
deps =
    requests>=2.34.2
    PyYAML>=6.0.3
    python-nmap>=0.7.1
    dnspython>=2.8.0
    PyGObject>=3.56.3
commands =
    python -m unittest discover -s tests

[testenv:lint]
deps =
    ruff
commands =
    ruff check .
